# Generated by Django 5.1.7 on 2025-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_contest_delete_contestant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
