# Generated by Django 5.1.7 on 2025-03-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alter_contest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
